version: '1.0'
build_script:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: dist
  on:
    branch: main
