version: 1.0.{build}
image: Visual Studio 2019

build_script:
  - npm install
  - npm run build

environment:
  trello:
    secure: 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            

  deploy:
    - provider: GitHubPages
      repository: Elizabess/trello-clone
      branch: gh-pages
      folder: dist
      on:
        branch: main 
   
