version: 1.0.{build}
image: Visual Studio 2019

build_script:
  - npm install
  - npm run build

environment:
  trello:
  secure: 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            

deploy:
  provider: GitHubPages
  github_token: $trello 
  local_dir: dist                
  on:
    branch: main  
  forse_push: true  