version: '1.1'
image: Visual Studio 2019

build_script:
  - npm install
  - npm run build

deploy:
  provider: Pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: main
