version: 1.0.{build}
image: Visual Studio 2019

build_script:
  - npm install
  - npm run build

deploy:
  provider: GitHubPages
  github_token: $trello 
  local_dir: dist                
  on:
    branch: main    

environment:
  trello:
  secure: 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            
